### ISSUE TITLE
在docker里运行openwrt | 且听风吟

### ISSUE THREAD

**Issue by saltfishh** [saltfishh/blog-comments#2]
https://blog.charons.work/posts/db1132b0-4e36-11eb-bbe3-c117a7825fa4/ 

 在linux物理主机里将openwrt放在docker里运行

**Comment by CyrusYip** [comment]
我在 x86 的 Arch Linux 用 docker 运行 OpenWrt，宿主机无法通过容器的 ip 访问 OpenWrt 管理界面，用其他设备倒是可以。看了这篇文章末尾，解决了这个问题。谢谢你，我搜好久都没找到方法，终于在你这解决了。

**Comment by saltfishh** [comment]
不客气😋.
没想到博客还有人看...

Cyrus Yip ***@***.***> 于 2022年4月20日周三 22:55写道：
